/**/bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: <prefix>map
    robot_base_frame: <prefix>base_link
    odom_topic: /<prefix>odom
    bt_loop_duration: 10
    default_server_timeout: 20
    wait_for_service_timeout: 10000
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_compute_path_through_poses_action_bt_node
      - nav2_smooth_path_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_assisted_teleop_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_drive_on_heading_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_globally_updated_goal_condition_bt_node
      - nav2_is_path_valid_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_controller_bt_node
      - nav2_speed_controller_bt_node
      - nav2_truncate_path_action_bt_node
      - nav2_truncate_path_local_action_bt_node
      - nav2_goal_updater_node_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_round_robin_node_bt_node
      - nav2_transform_available_condition_bt_node
      - nav2_time_expired_condition_bt_node
      - nav2_path_expiring_timer_condition
      - nav2_distance_traveled_condition_bt_node
      - nav2_single_trigger_bt_node
      - nav2_goal_updated_controller_bt_node
      - nav2_is_battery_low_condition_bt_node
      - nav2_navigate_through_poses_action_bt_node
      - nav2_navigate_to_pose_action_bt_node
      - nav2_remove_passed_goals_action_bt_node
      - nav2_planner_selector_bt_node
      - nav2_controller_selector_bt_node
      - nav2_goal_checker_selector_bt_node
      - nav2_controller_cancel_bt_node
      - nav2_path_longer_on_approach_bt_node
      - nav2_wait_cancel_bt_node
      - nav2_spin_cancel_bt_node
      - nav2_back_up_cancel_bt_node
      - nav2_assisted_teleop_cancel_bt_node
      - nav2_drive_on_heading_cancel_bt_node
      - nav2_is_battery_charging_condition_bt_node

/**/controller_server:
  ros__parameters:
    controller_frequency: 20.0
    costmap_update_timeout: 0.30
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["general_goal_checker"] 
    controller_plugins: ["FollowPath"]
    use_realtime_priority: false
    speed_limit_topic: "speed_limit"
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 30.0
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"
      time_steps: 40
      model_dt: 0.05
      batch_size: 1500
      ax_max: 3.0
      ax_min: -3.0
      ay_max: 3.0
      ay_min: -3.0
      az_max: 3.5
      vx_std: 0.3
      vy_std: 0.2
      wz_std: 0.5
      vx_max: 0.8
      vx_min: -0.3
      vy_max: 0.5
      wz_max: 1.9
      iteration_count: 2
      prune_distance: 1.7
      transform_tolerance: 0.1
      temperature: 0.5
      gamma: 0.015
      motion_model: "DiffDrive"
      visualize: true
      publish_optimal_trajectory: true
      regenerate_noises: true
      TrajectoryVisualizer:
        trajectory_step: 5
        time_step: 3
      critics:
        [
          "ConstraintCritic",
          "CostCritic",
          "GoalCritic",
          "GoalAngleCritic",
          "PathAlignCritic",
          "PathFollowCritic",
          "PathAngleCritic",
          "PreferForwardCritic",
        ]
      ConstraintCritic:
        enabled: true
        cost_power: 1
        cost_weight: 4.0
      GoalCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: 1.4
      GoalAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.0
        threshold_to_consider: 0.5
      PreferForwardCritic:
        enabled: true
        cost_power: 1
        cost_weight: 6.0
        threshold_to_consider: 0.5
      CostCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.81
        near_collision_cost: 253
        critical_cost: 300.0
        consider_footprint: true
        collision_cost: 1000000.0
        near_goal_distance: 1.0
        trajectory_point_step: 2
      PathAlignCritic:
        enabled: true
        cost_power: 1
        cost_weight: 10.0
        max_path_occupancy_ratio: 0.05
        trajectory_point_step: 4
        threshold_to_consider: 0.5
        offset_from_furthest: 20
        use_path_orientations: false
      PathFollowCritic:
        enabled: true
        cost_power: 1
        cost_weight: 8.0
        offset_from_furthest: 5
        threshold_to_consider: 1.4
      PathAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 2.0
        offset_from_furthest: 4
        threshold_to_consider: 0.5
        max_angle_to_furthest: 1.0
        mode: 0

/**/local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 2.0
      publish_frequency: 2.0
      global_frame: <prefix>odom
      robot_base_frame: <prefix>base_link
      rolling_window: true
      width: 4
      height: 4
      resolution: 0.1
      footprint: "[[0.360, 0.20], [0.360, -0.20], [-0.450, -0.20], [-0.450, 0.20]]"
      transform_tolerance: 0.5

      plugins: ["obstacle_layer_front", "obstacle_layer_back", "inflation_layer"]

      obstacle_layer_front:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        footprint_clearing_enabled: true
        observation_sources: scan_front
        scan_front:
          data_type: "LaserScan"
          topic: "/<prefix>front_camera/scan"
          marking: true
          clearing: true
          obstacle_max_range: 3.0
          obstacle_min_range: 0.3
          raytrace_max_range: 3.5
          raytrace_min_range: 0.25
          min_obstacle_height: 0.1
          max_obstacle_height: 2.0
          inf_is_valid: false
          clear_on_max_reading: true

      obstacle_layer_back:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        footprint_clearing_enabled: true
        observation_sources: scan_back
        scan_back:
          data_type: "LaserScan"
          topic: "/<prefix>back_camera/scan"     # e.g. "/back_d455/scan"
          marking: true
          clearing: true
          obstacle_max_range: 3.0
          obstacle_min_range: 0.3
          raytrace_max_range: 3.5
          raytrace_min_range: 0.25
          min_obstacle_height: 0.1
          max_obstacle_height: 2.0
          inf_is_valid: false
          clear_on_max_reading: true

      denoise_layer:
        plugin: "nav2_costmap_2d::DenoiseLayer"
        enabled: False
        minimal_group_size: 2
        group_connectivity_type: 8

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 1.0
        inflation_radius: 0.55

      always_send_full_costmap: True
      service_introspection_mode: "disabled"
      
/**/global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 5.0
      global_frame: <prefix>map
      robot_base_frame: <prefix>base_link
      resolution: 0.05
      footprint: "[[0.360, 0.20], [0.360, -0.20], [-0.450, -0.20], [-0.450, 0.20]]"
      track_unknown_space: true
      transform_tolerance: 2.0
      plugins: ["static_layer", "obstacle_layer_front", "obstacle_layer_back", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        footprint_clearing_enabled: true
      obstacle_layer_front:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        footprint_clearing_enabled: true
        max_obstacle_height: 0.5
        observation_sources: scan_front
        scan_front:
          data_type: "LaserScan"
          topic: "/<prefix>front_camera/scan"    # e.g. "/d455/scan"
          marking: true
          clearing: true
          obstacle_max_range: 3.0
          obstacle_min_range: 0.0
          raytrace_max_range: 3.5
          raytrace_min_range: 0.0
          min_obstacle_height: 0.1
          max_obstacle_height: 2.0
          inf_is_valid: false
          clear_on_max_reading: true
          expected_update_rate: 5.0

      obstacle_layer_back:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        footprint_clearing_enabled: true
        max_obstacle_height: 0.5
        observation_sources: scan_back
        scan_back:
          data_type: "LaserScan"
          topic: "/<prefix>back_camera/scan"     # e.g. "/back_d455/scan"
          marking: true
          clearing: true
          obstacle_max_range: 3.0
          obstacle_min_range: 0.0
          raytrace_max_range: 3.5
          raytrace_min_range: 0.0
          min_obstacle_height: 0.1
          max_obstacle_height: 2.0
          inf_is_valid: false
          clear_on_max_reading: true
          expected_update_rate: 5.0
      denoise_layer:
        plugin: "nav2_costmap_2d::DenoiseLayer"
        enabled: True
        minimal_group_size: 6
        group_connectivity_type: 8
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.6
      always_send_full_costmap: True
      service_introspection_mode: "disabled"

/**/map_server:
  ros__parameters:
    # yaml_filename: ""
    service_introspection_mode: "disabled"

/**/map_saver:
  ros__parameters:
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True
    service_introspection_mode: "disabled"

/**/planner_server:
  ros__parameters:
    planner_plugins: ["GridBased"]
    #GridBased:
    #  plugin: 'nav2_navfn_planner/NavfnPlanner'
    GridBased:
      plugin: "nav2_smac_planner/SmacPlanner2D"
      allow_unknown: false
      use_astar: true
      motion_model_for_search: "VON_NEUMANN"
      downsample_costmap: false
      tolerance: 0.1
      max_iterations: 500000
      cost_travel_multiplier: 30.0

/**/smoother_server:
  ros__parameters:
    smoother_plugins: ["simple_smoother", "route_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      refinement_num: 2
      enforce_path_inversion: True
      do_refinement: True
    route_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      refinement_num: 5
      enforce_path_inversion: False
      do_refinement: True

/**/behavior_server:
  ros__parameters:
    local_costmap_topic: /<prefix>local_costmap/costmap_raw
    global_costmap_topic: /<prefix>global_costmap/costmap_raw
    local_footprint_topic: /<prefix>local_costmap/published_footprint
    global_footprint_topic: /<prefix>global_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins:
      ["spin", "backup", "drive_on_heading", "assisted_teleop", "wait"]
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
      acceleration_limit: 2.5
      deceleration_limit: -2.5
      minimum_speed: 0.10
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
      acceleration_limit: 2.5
      deceleration_limit: -2.5
      minimum_speed: 0.10
    wait:
      plugin: "nav2_behaviors/Wait"
    assisted_teleop:
      plugin: "nav2_behaviors/AssistedTeleop"
    local_frame: <prefix>odom
    global_frame: <prefix>map
    robot_base_frame: <prefix>base_link
    transform_tolerance: 0.1
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

/**/waypoint_follower:
  ros__parameters:
    loop_rate: 20
    stop_on_failure: false
    service_introspection_mode: "disabled"
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200

/**/route_server:
  ros__parameters:
    boundary_radius_to_achieve_node: 1.0
    radius_to_achieve_node: 2.0
    smooth_corners: true
    operations: ["AdjustSpeedLimit", "ReroutingService", "CollisionMonitor"]
    ReroutingService:
      plugin: "nav2_route::ReroutingService"
    AdjustSpeedLimit:
      plugin: "nav2_route::AdjustSpeedLimit"
    CollisionMonitor:
      plugin: "nav2_route::CollisionMonitor"
      max_collision_dist: 3.0
    edge_cost_functions: ["DistanceScorer", "CostmapScorer"]
    DistanceScorer:
      plugin: "nav2_route::DistanceScorer"
    CostmapScorer:
      plugin: "nav2_route::CostmapScorer"

/**/velocity_smoother:
  ros__parameters:
    smoothing_frequency: 20.0
    scale_velocities: False
    feedback: "OPEN_LOOP"
    max_velocity: [0.5, 0.0, 2.0]
    min_velocity: [-0.5, 0.0, -2.0]
    max_accel: [2.5, 0.0, 3.2]
    max_decel: [-2.5, 0.0, -3.2]
    odom_topic: "/<prefix>odom" # "odom"
    odom_duration: 0.1
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0

/**/collision_monitor:
  ros__parameters:
    base_frame_id: "<prefix>base_link" # base_footprint
    odom_frame_id: "<prefix>odom"
    cmd_vel_in_topic: "/<prefix>cmd_vel_smoothed"
    cmd_vel_out_topic: "/<prefix>cmd_vel"
    state_topic: "/<prefix>collision_monitor_state"
    transform_tolerance: 0.2
    source_timeout: 1.0
    base_shift_correction: True
    stop_pub_timeout: 2.0
    polygons: ["FootprintApproach"]
    FootprintApproach:
      type: "polygon"
      action_type: "approach"
      footprint_topic: "local_costmap/published_footprint"
      time_before_collision: 1.2
      simulation_time_step: 0.1
      min_points: 6
      visualize: False
      enabled: True
    observation_sources: ["scan"]
    scan:
      type: "scan"
      topic: "/<prefix>scan"
      min_height: 0.15
      max_height: 2.0
      enabled: True

/**/docking_server:
  ros__parameters:
    controller_frequency: 50.0
    initial_perception_timeout: 5.0
    wait_charge_timeout: 5.0
    dock_approach_timeout: 30.0
    undock_linear_tolerance: 0.05
    undock_angular_tolerance: 0.1
    max_retries: 3
    base_frame: "<prefix>base_link"
    fixed_frame: "<prefix>odom"
    dock_prestaging_tolerance: 0.5
    service_introspection_mode: "disabled"

    dock_plugins: ["simple_charging_dock"]
    simple_charging_dock:
      plugin: "opennav_docking::SimpleChargingDock"
      docking_threshold: 0.05
      staging_x_offset: -0.7
      use_external_detection_pose: true
      use_battery_status: false # true
      use_stall_detection: false # true
      dock_direction: "forward"

      external_detection_timeout: 1.0
      external_detection_translation_x: -0.18
      external_detection_translation_y: 0.0
      external_detection_rotation_roll: -1.57
      external_detection_rotation_pitch: -1.57
      external_detection_rotation_yaw: 0.0
      filter_coef: 0.1

    controller:
      k_phi: 3.0
      k_delta: 2.0
      v_linear_min: 0.15
      v_linear_max: 0.15
      use_collision_detection: true
      costmap_topic: "/<prefix>local_costmap/costmap_raw"
      footprint_topic: "/<prefix>local_costmap/published_footprint"
      transform_tolerance: 0.1
      projection_time: 5.0
      simulation_step: 0.1
      dock_collision_threshold: 0.3

/**/loopback_simulator:
  ros__parameters:
    base_frame_id: "<prefix>base_link" 
    odom_frame_id: "<prefix>odom"
    map_frame_id: "<prefix>map"
    scan_frame_id: "<prefix>base_scan" 
    update_duration: 0.02
    scan_range_min: 0.05
    scan_range_max: 30.0
    scan_angle_min: -3.1415
    scan_angle_max: 3.1415
    scan_angle_increment: 0.02617
    scan_use_inf: true